//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public string departure { get; set; }
        public string destination { get; set; }
        public string weight { get; set; }
        public string deliver_date { get; set; }
        public string ship_num { get; set; }
        public string status { get; set; }
    }
}
